=== inf22tig02/inf22tig02/archives/animais.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.animais.org"
    xmlns:tns="http://www.w3.rg/2001/XMLSchema"
    elementFormDefault="qualified">
    <xs:element name="mitologia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name= "mito" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="nome" maxOccurs="unbounded" minOccurs="0"></xs:element>
                            <xs:element type="xs:string" name="religiao" maxOccurs="unbounded" minOccurs="0"></xs:element>
                            <xs:element name="imagem" maxOccurs="unbounded" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:anyURI">
                                        <xs:pattern value="(.)+\.(gif|jpg|jpeg|bmp)"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:string" name="especie" maxOccurs="unbounded" minOccurs="0"></xs:element>
                            <xs:element type="xs:string" name="descricao" maxOccurs="unbounded" minOccurs="0"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>    
</xs:schema>

=== inf22tig02/inf22tig02/animais.xml
<?xml version="1.0" encoding="UTF-8"?>
<mitologia xmlns ="http://www.animais.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.animais.org
                             animais.xsd">
    <mito>
        <nome>Anubis</nome>
        <religiao>Egipcia</religiao>
        <imagem>anubis.jpg</imagem>
        <especie>Chacal</especie>
        <descricao>Deus dos mortos e moribundos</descricao>
    </mito>
    <mito>
        <nome>Ra</nome>
        <religiao>Egipcia</religiao>
        <imagem>anubis.jpg</imagem>
        <especie>Possivelmente um Falcão-Peregrino</especie>
        <descricao>Deus do Sol</descricao>
    </mito>
    <mito>
        <nome>Sekhmet</nome>
        <religiao>Egipcia</religiao>
        <imagem>anubis.jpg</imagem>
        <especie>Leoa</especie>
        <descricao>Deusa da Guerra</descricao>
    </mito>
    <mito>
        <nome>Pegaso</nome>
        <religiao>Grega</religiao>
        <imagem>pegasus.jpg</imagem>
        <especie>Cavalo</especie>
        <descricao>Cavalo alado, simbolo da imortalidade</descricao>
    </mito>
    <mito>
        <nome>Leão de nemeia</nome>
        <religiao>Grega</religiao>
        <imagem>lion1.jpg</imagem>
        <especie>Leão</especie>
        <descricao>Leão com um couro impenetrável</descricao>
    </mito>
    <mito>
        <nome>Cerberus</nome>
        <religiao>Grega</religiao>
        <imagem>pegasus.jpg</imagem>
        <especie>Cachorro</especie>
        <descricao>Cachorro de três cabeças que protege os portões do sub-mundo</descricao>
    </mito>
    <mito>
        <nome>Fenrir</nome>
        <religiao>Nordica</religiao>
        <imagem>fenrir.jpg</imagem>
        <especie>Lobo</especie>
        <descricao>Um lobo monstruoso que foi acorrentado e devorou a mão direita do deus Tyr</descricao>
    </mito>
    <mito>
        <nome>Ratatoskr</nome>
        <religiao>Nordica</religiao>
        <imagem>ratatoskr.jpg</imagem>
        <especie>Esquilo</especie>
        <descricao>Esquilo que escala a arvore da vida Yggdrasil e repassa mensagens</descricao>
    </mito>
    <mito>
        <nome>Huginn e Munin</nome>
        <religiao>Nordica</religiao>
        <imagem>huginnmuninn.jpg</imagem>
        <especie>Corvos</especie>
        <descricao>Par de corvos que viajam o mundo nordico e relatam seus acontecimentos a Odin</descricao>
    </mito>
</mitologia>

=== inf22tig02/inf22tig02/archives/animais.xml
<?xml version="1.0" encoding="UTF-8"?>
<mitologia xmlns ="http://www.animais.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.animais.org
                             animais.xsd">
    <mito>
        <nome>Anubis</nome>
        <religiao>Egipcia</religiao>
        <imagem>anubis.jpg</imagem>
        <especie>Chacal</especie>
        <descricao>Deus dos mortos e moribundos</descricao>
    </mito>
    <mito>
        <nome>Pegaso</nome>
        <religiao>Grega</religiao>
        <imagem>pegasus.jpg</imagem>
        <especie>Cavalo</especie>
        <descricao>Cavalo alado, simbolo da imortalidade</descricao>
    </mito>
    <mito>
        <nome>Fenrir</nome>
        <religiao>Nordica</religiao>
        <imagem>fenrir.jpg</imagem>
        <especie>Lobo</especie>
        <descricao>Um lobo monstruoso que foi acorrentado e devorou a m√£o direita do deus Tyr</descricao>
    </mito>
</mitologia>
